name: Continuous Integration

on:
  pull_request

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write "**/*.{ts,tsx,json}"

      - name: Commit and Push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add .
          git commit -m "chore: apply prettier formatting"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
