name: Continuous Integration

on:
  pull_request

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
            ref: ${{ github.event.pull_request.head.ref }}

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write "**/*.{ts,tsx,json}"
